name: Publish My Test Hashnode Blog Posts
on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Convert changed files to JSON array
        id: convert-changed-files
        run: |
          echo "CHANGED_FILES_JSON=$(echo '[\"${{ steps.changed-files.outputs.all_changed_files }}\"]' | sed 's/ /\",\"/g')" >> $GITHUB_ENV
          echo "DELETED_FILES_JSON=$(echo '[\"${{ steps.changed-files.outputs.deleted_files }}\"]' | sed 's/ /\",\"/g')" >> $GITHUB_ENV

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Publish to Hashnode
        id: publish
        uses: OmenApps/publish-github-to-hashnode@v1.8
        with:
          access-token: ${{ secrets.HASHNODE_ACCESS_TOKEN }}
          changed-files: ${{ env.CHANGED_FILES_JSON }}
          deleted-files: ${{ env.DELETED_FILES_JSON }}
          publication-host: 'test.jacklinke.com'

      - name: Get the output JSON
        run: echo "${{ steps.publish.outputs.result_json }}"
